# Generated by Django 6.0.5 on 2026-05-17 16:18

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, upload_to=posts.models.get_image_upload_path, verbose_name='Foto'),
        ),
    ]
