# Generated by Django 6.0.5 on 2026-05-17 16:32

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.get_image_upload_path, verbose_name='Foto'),
        ),
    ]
